"""Add number of questions to quizzes

Revision ID: 957d5f5f75e2
Revises: 3cfa9287e331
Create Date: 2026-09-29 15:48:55.519417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957d5f5f75e2'
down_revision = '3cfa9287e331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_questions',sa.Integer(),nullable=False,server_default='10'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('number_of_questions')

    # ### end Alembic commands ###
